
server:
  port: '10005'

spring:
  application:
    name: email-service
  kafka:
    bootstrap-servers: 'kafka:29092'
    consumer:
      group-id: default

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service-app:8061/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
    jmx:
      exposure:
        include: '*'
  security:
    enabled: false
