
server:
  port: '10002'

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
        globally_quoted_identifiers: true
  datasource:
    username: admin
    password: pass
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  kafka:
    bootstrap-servers: 'kafka:29092'

springdoc:
  swagger-ui:
    path: /api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service-app:8061/eureka/
