version: "3.7"

volumes:
  app-vol:
  db-vol:
  
networks:
  kafka-net:
    external:
      name: kafka-net

services:
  product_service:
    build: .
    restart: always
    container_name: product-service-app
    ports:
      - 10001:10001
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://product_service_db:3306/hs-product?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - product_service_db
    links:
      - product_service_db:app_db
    volumes:
      - app-vol:/home/node/product-service-app
    networks:
      - kafka-net
      
  product_service_db:
    image: "mysql:8.0"
    restart: always
    container_name: product-service-db
    ports:
      - 20001:3306
    environment:
      MYSQL_DATABASE: hs-product
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqld", "--version"]
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - kafka-net
 