version: "3.7"

volumes:
  app-vol:
  db-vol:
  
networks:
  kafka-net:
    external:
      name: kafka-net
      
services:
  api_service:
    build: .
    restart: always
    ports:
      - 10004:10004
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/hs-order?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
    volumes:
      - app-vol:/home/node/order-service-app
    networks:
      - kafka-net
      
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 20004:3306
    environment:
      MYSQL_DATABASE: hs-order
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqld", "--version"]
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - kafka-net
