version: "3.7"

volumes:
  app-vol:
  
networks:
  kafka-net:
    external:
      name: kafka-net
  
services:
  enail_service:
    build: .
    restart: always
    container_name: email-service-app
    ports:
      - 10005:10005
    volumes:
      - app-vol:/home/node/email-service-app
    networks:
      - kafka-net
