version: "3.7"

volumes:
  app-vol:
  db-vol:
  
networks:
  kafka-net:
    external:
      name: kafka-net
  
services:
  user_service:
    build: .
    restart: always
    container_name: user-service-app
    ports:
      - 10003:10003
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user_service_db:3306/hs-user?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - user_service_db
    links:
      - user_service_db:app_db
    volumes:
      - app-vol:/home/node/user-service-app
    networks:
      - kafka-net
      
  user_service_db:
    image: "mysql:8.0"
    restart: always
    container_name: user-service-db
    ports:
      - 20003:3306
    environment:
      MYSQL_DATABASE: hs-user
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqld", "--version"]
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - kafka-net
