version: "3.7"

volumes:
  app-vol:
  
networks:
  kafka-net:
    external:
      name: kafka-net
  
services:
  gateway_service:
    build: .
    restart: always
    container_name: gateway-service-app
    ports:
      - 8080:8080
    volumes:
      - app-vol:/home/node/gateway-service-app
    networks:
      - kafka-net
