
scrape_configs:
  - job_name: 'gateway-service'
    scrape_interval: 10s
    scrape_timeout: 7s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway-service-app:8080']
        labels:
          group: 'gateway'
  - job_name: 'product-service'
    scrape_interval: 10s
    scrape_timeout: 7s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product-service-app:10001']
        labels:
          group: 'product'
  - job_name: 'stock-service'
    scrape_interval: 10s
    scrape_timeout: 7s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['stock-service-app:10002']
        labels:
          group: 'stock'
  - job_name: 'user-service'
    scrape_interval: 10s
    scrape_timeout: 7s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service-app:10003']
        labels:
          group: 'user'
  - job_name: 'order-service'
    scrape_interval: 10s
    scrape_timeout: 7s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['order-service-app:10004']
        labels:
          group: 'order'
  - job_name: 'email-service'
    scrape_interval: 10s
    scrape_timeout: 7s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['email-service-app:10005']
        labels:
          group: 'email'
