version: "3.7"

volumes:
  app-vol:
  db-vol:

networks:
  kafka-net:
    external:
      name: kafka-net

services:
  stock_service:
    build: .
    restart: always
    container_name: stock-service-app
    ports:
      - 10002:10002
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://stock_service_db:3306/hs-stock?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - stock_service_db
    links:
      - stock_service_db:app_db
    volumes:
      - app-vol:/home/node/stock-service-app
    networks:
      - kafka-net
      
  stock_service_db:
    image: "mysql:8.0"
    restart: always
    container_name: stock-service-db
    ports:
      - 20002:3306
    environment:
      MYSQL_DATABASE: hs-stock
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqld", "--version"]
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - kafka-net
 