version: "3.7"
volumes:
  app-vol:
  db-vol:
services:
  api_service:
    build: .
    restart: always
    ports:
      - 10002:10002
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/hs-stock?useUnicode=yes&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    depends_on:
      - mysql_db
    links:
      - mysql_db:app_db
    volumes:
      - app-vol:/home/node/order-service-app
      
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 20002:3306
    environment:
      MYSQL_DATABASE: hs-stock
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqld", "--version"]
    volumes:
      - db-vol:/var/lib/mysql
 